baseURL = 'https://jaewoo-lee.com/'
languageCode = 'en-us'
title = 'jaewoolee'
theme = "hugo-theme-console"

[params]
  description = "Hello. I'm Jaewoo Lee."
  animateStyle = "animate-fade-up" 

[[params.navlinks]]
  name = "About"
  url = "/about/"

[[params.navlinks]]
  name = "Project"
  url = "/project/"

[[params.navlinks]]
  name = "CV"
  url = "/CV/"